title: Site
sections:
  pages:
    type: pages
  content:
    type: fields
    fields:
      description:
        label: Description
        type: text
      facebook:
        label: Facebook
        type: url
        width: 1/3
      twitter:
        label: Twitter
        type: url
        width: 1/3
      instagram:
        label: Instagram
        type: url
        width: 1/3
