title: Site
sections:
  details:
    type: fields
    fields:
      description:
        label: Description (for Google)
        type: text
        width: 1/2
      keywords:
        label: Keywords (for Google, max. 6)
        type: text
        width: 1/2
      email:
        label: Email
        type: email
        width: 1/3
      facebook:
        label: Facebook
        type: url
        width: 1/3
      instagram:
        label: Instagram
        type: url
        width: 1/3
  pages:
    label: Pages
    type: pages
    sortable: true
    status: all
